// ===================================================
//  BenBooks Plus – Real book data from sachbanquyen.com.vn
// ===================================================

const BOOKS_DATA = [
  { id:13, title:"Kiến thức Tiếng Anh trọng tâm: Quá khứ hoàn thành tiếp diễn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.5, views:1205, editions:10, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:120, coverColor:"#E8D4A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/26/image-20260326114914102.png", description:"Tài liệu học tập chi tiết về thì quá khứ hoàn thành tiếp diễn trong Tiếng Anh.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:14, title:"Kiến thức Tiếng Anh trọng tâm: Tương lai hoàn thành tiếp diễn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Audio", isVip:false, price:"5.000 đ", rating:4.5, views:1540, editions:12, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:120, coverColor:"#C5D8A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/25/image-20260325090916895.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:15, title:"Kiến thức Tiếng Anh trọng tâm: Danh từ đếm được, không đếm được", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"20.000 đ", rating:4.8, views:3200, editions:34, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:150, coverColor:"#F0D5A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/25/image-20260325082812609.png", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:16, title:"Kiến thức Tiếng Anh trọng tâm: Tương lai gần", author:"Nhiều Tác Giả", publisher:"Benito", type:"Audio", isVip:false, price:"5.000 đ", rating:4.2, views:900, editions:8, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:100, coverColor:"#D0E8F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319162808613.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:17, title:"Kiến thức Tiếng Anh trọng tâm: Động từ nguyên mẫu (To verb)", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.4, views:1100, editions:9, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:110, coverColor:"#F5C0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319162838695.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:18, title:"Toán tư duy tiền tiểu học", author:"Nhiều Tác Giả", publisher:"Benito", type:"Audio", isVip:false, price:"5.000 đ", rating:4.9, views:5600, editions:120, categories:["Giáo dục"], genre:"Sách tham khảo", pages:80, coverColor:"#FFE0B0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/19/image-20260319120355074.jpg", description:"Giúp trẻ phát triển tư duy từ sớm.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:19, title:"Kiến thức Tiếng Anh trọng tâm: Hiện tại hoàn thành", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"20.000 đ", rating:4.7, views:4500, editions:42, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:160, coverColor:"#D8F0D0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/16/image-20260316123652646.png", description:"Tài liệu ôn luyện chuyên sâu.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:20, title:"Kiến thức Tiếng Anh trọng tâm: Tương lai hoàn thành", author:"Nhiều Tác Giả", publisher:"Benito", type:"Audio", isVip:false, price:"5.000 đ", rating:4.3, views:1250, editions:14, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:115, coverColor:"#E0D0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/16/image-20260316153417345.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:21, title:"Kiến thức Tiếng Anh trọng tâm: Quá khứ hoàn thành", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.4, views:1800, editions:18, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:125, coverColor:"#F0E0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/13/image-20260313162537925.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:22, title:"Kiến thức Tiếng Anh trọng tâm: Tương lai đơn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Audio", isVip:false, price:"20.000 đ", rating:4.8, views:5400, editions:60, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:140, coverColor:"#C0E0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/10/image-20260310151314926.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:23, title:"Kiến thức Tiếng Anh trọng tâm: Tương lai tiếp diễn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.1, views:750, editions:5, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:105, coverColor:"#E8D4A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/7/image-20260307100233319.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:24, title:"Kiến thức Tiếng Anh trọng tâm: Quá khứ tiếp diễn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Audio", isVip:false, price:"20.000 đ", rating:4.6, views:3100, editions:28, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:150, coverColor:"#C5D8A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306083737170.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:25, title:"Kiến thức Tiếng Anh trọng tâm: Quá khứ đơn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"20.000 đ", rating:4.9, views:8200, editions:95, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:160, coverColor:"#F0D5A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306085422183.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:26, title:"Kiến thức Tiếng Anh trọng tâm: Hiện tại tiếp diễn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.5, views:4500, editions:33, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:135, coverColor:"#D0E8F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/6/image-20260306141601047.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:27, title:"Kiến thức Tiếng Anh trọng tâm: Hiện tại đơn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.8, views:12000, editions:154, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:150, coverColor:"#F5C0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/3/5/image-20260305102435472.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:28, title:"Cuộc phiêu lưu của chú Kiến Vàng", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"10.455 đ", rating:4.7, views:3100, editions:26, categories:["Sách Thiếu nhi"], genre:"Truyện tranh", pages:50, coverColor:"#FFE0B0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/2/27/image-20260227144734328.jpg", description:"Truyện kể cho bé.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:29, title:"Kiến thức Tiếng Anh trọng tâm: Tính từ miêu tả", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.3, views:1800, editions:15, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:110, coverColor:"#D8F0D0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/2/27/image-20260227091856276.jpg", description:"Tài liệu học tập chi tiết.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:30, title:"Cẩm nang ôn thi tốt nghiệp tin học: Website HTML (tập 1)", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.8, views:2900, editions:31, categories:["Sách tham khảo","Giáo dục","Công nghệ thông tin"], genre:"Tài liệu chuyên ngành", pages:200, coverColor:"#E0D0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/2/7/image-20260207090637354.png", description:"Tài liệu chuyên sâu ngành lập trình web.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:31, title:"Cẩm nang ôn thi tốt nghiệp tin học: Website CSS (tập 1)", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.7, views:3300, editions:38, categories:["Sách tham khảo","Giáo dục","Công nghệ thông tin"], genre:"Tài liệu chuyên ngành", pages:220, coverColor:"#F0E0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2026/2/7/image-20260207090956096.png", description:"Tài liệu chuyên môn hữu ích.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:32, title:"Những vĩ nhân trong lịch sử: Ernest Hemingway", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.9, views:15400, editions:205, categories:["Tiểu sử - Hồi ký"], genre:"Kiến thức chung", pages:350, coverColor:"#C0E0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/11/27/image-book-20251127081656947.png", description:"Câu chuyện về cuộc đời của nhà văn vĩ đại.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:33, title:"Phương tiện giao thông quanh ta", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.8, views:1250, editions:15, categories:["Sách thiếu nhi","Giáo dục"], genre:"Sách thiếu nhi", pages:50, coverColor:"#E8D4A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/8/11/image-book-20250811140652361.jpg", description:"Sách giúp bé tìm hiểu phương tiện giao thông.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:34, title:"Việt Nam muôn màu", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.9, views:3400, editions:22, categories:["Sách thiếu nhi","Văn hóa"], genre:"Sách thiếu nhi", pages:60, coverColor:"#C5D8A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704100405005.jpg", description:"Giới thiệu văn hóa Việt Nam.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:35, title:"Nghề nghiệp tương lai: Logistics - cung ứng", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.6, views:1800, editions:12, categories:["Giáo dục","Hướng nghiệp"], genre:"Hướng nghiệp", pages:90, coverColor:"#F0D5A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704094800703.jpg", description:"Tìm hiểu ngành logistics.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:36, title:"Nghề nghiệp tương lai: Du lịch", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.5, views:2200, editions:18, categories:["Giáo dục","Hướng nghiệp"], genre:"Hướng nghiệp", pages:90, coverColor:"#D0E8F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704094442151.jpg", description:"Tìm hiểu ngành du lịch.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:37, title:"Nghề nghiệp tương lai: Tài nguyên môi trường", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.4, views:1500, editions:10, categories:["Giáo dục","Hướng nghiệp"], genre:"Hướng nghiệp", pages:90, coverColor:"#F5C0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095249548.jpg", description:"Tìm hiểu ngành môi trường.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:38, title:"Tết thiếu nhi", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.9, views:5600, editions:40, categories:["Sách thiếu nhi"], genre:"Sách thiếu nhi", pages:40, coverColor:"#FFE0B0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095939163.jpg", description:"Khám phá tết thiếu nhi.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:39, title:"Nghề nghiệp tương lai: Nông nghiệp công nghệ cao", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.5, views:1300, editions:11, categories:["Giáo dục","Hướng nghiệp"], genre:"Hướng nghiệp", pages:90, coverColor:"#D8F0D0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-2025070409491636.jpg", description:"Tìm hiểu ngành nông nghiệp CNC.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:40, title:"Tết Trung thu", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.9, views:6500, editions:45, categories:["Sách thiếu nhi"], genre:"Sách thiếu nhi", pages:45, coverColor:"#E0D0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704100127787.jpg", description:"Khám phá trăng rằm.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:41, title:"Khám phá Quốc kì", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.8, views:3100, editions:20, categories:["Giáo dục"], genre:"Kiến thức", pages:60, coverColor:"#F0E0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704093255109.jpg", description:"Nhận biết cờ các nước.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:42, title:"Nghề nghiệp tương lai: Phân tích dữ liệu", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.7, views:4500, editions:33, categories:["Giáo dục","Hướng nghiệp"], genre:"Hướng nghiệp", pages:100, coverColor:"#C0E0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095029845.jpg", description:"Tìm hiểu ngành Data.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:43, title:"Tết Nguyên đán", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.9, views:8000, editions:55, categories:["Sách thiếu nhi"], genre:"Sách thiếu nhi", pages:50, coverColor:"#E8D4A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/7/4/image-book-20250704095744719.jpg", description:"Khám phá tết cổ truyền.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:44, title:"Lạc quanh thế giới: Lạc khám phá Nam Mỹ bí ẩn", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.8, views:4100, editions:22, categories:["Khám phá","Văn hóa"], genre:"Du ký", pages:120, coverColor:"#C5D8A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/8/8/image-book-20250808083006201.png", description:"Hành trình đến Nam Mỹ.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:45, title:"Lạc quanh thế giới: Lạc tới Thổ Nhĩ Kỳ cổ kính", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.6, views:3200, editions:18, categories:["Khám phá","Văn hóa"], genre:"Du ký", pages:120, coverColor:"#F0D5A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320100948394.png", description:"Khám phá vùng đất giao thoa.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:46, title:"Lạc quanh thế giới: Lạc tới New Zealand và Australia", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.7, views:3800, editions:21, categories:["Khám phá","Văn hóa"], genre:"Du ký", pages:120, coverColor:"#D0E8F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320101301424.png", description:"Khám phá châu Đại Dương.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:47, title:"Lạc quanh thế giới: Lạc tới nước Ý mộng mơ", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.9, views:5200, editions:30, categories:["Khám phá","Văn hóa"], genre:"Du ký", pages:120, coverColor:"#F5C0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-2025032009163242.png", description:"Lang thang ở kinh đô nghệ thuật.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:48, title:"Lạc quanh thế giới: Lạc vào Ai Cập huyền bí", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.8, views:4700, editions:25, categories:["Khám phá","Văn hóa"], genre:"Du ký", pages:120, coverColor:"#FFE0B0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/3/20/image-book-20250320101739797.png", description:"Bí ẩn lăng mộ Pharaoh.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:49, title:"Có thể bạn chưa biết: Ai là người phát hiện ra tia X", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.6, views:2900, editions:14, categories:["Khoa học"], genre:"Kiến thức", pages:80, coverColor:"#D8F0D0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317142940692.png", description:"Khám phá khoa học quanh ta.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:50, title:"Tìm hiểu các trường ĐH ở VN: ĐH Bách khoa Hà Nội", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.8, views:7500, editions:60, categories:["Giáo dục","Hướng nghiệp"], genre:"Tài liệu chuyên ngành", pages:150, coverColor:"#E0D0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/5/12/image-book-20250512094945531.png", description:"Tài liệu luyện thi và tìm hiểu.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:51, title:"Có thể bạn chưa biết: Chiếc máy ảnh đầu tiên", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.7, views:3100, editions:19, categories:["Khoa học"], genre:"Kiến thức", pages:80, coverColor:"#F0E0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317140914719.png", description:"Lịch sử công nghệ.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:52, title:"Có thể bạn chưa biết: Tàu Parker khám phá vũ trụ", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:4.8, views:4200, editions:25, categories:["Khoa học","Vũ trụ"], genre:"Kiến thức", pages:90, coverColor:"#C0E0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/3/17/image-book-20250317133017076.png", description:"Hành trình ra ngoài không gian.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:53, title:"Phân tích kiến thức cơ bản trong các văn bản", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"6.715 đ", rating:5, views:2100, editions:17, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:130, coverColor:"#E8D4A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/9/3/image-book-20250903105050594.jpg", description:"Tài liệu phân tích kiến thức cơ bản trong các văn bản Ngữ văn.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:54, title:"Hoạt động giáo dục ngoài giờ lên lớp 6", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"25.000 đ", rating:5, views:3400, editions:28, categories:["Giáo dục"], genre:"Giáo dục", pages:160, coverColor:"#C5D8A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/9/4/image-book-20250904152208067.jpg", description:"Tài liệu hỗ trợ hoạt động giáo dục ngoài giờ lên lớp.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:55, title:"Rửa tay cho sạch nào", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:5, views:4800, editions:52, categories:["Sách Thiếu nhi","Sức khoẻ"], genre:"Sách Thiếu nhi", pages:32, coverColor:"#D0E8F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/8/26/image-book-20250826112045728.jpg", description:"Sách tranh hướng dẫn bé cách rửa tay đúng cách.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:56, title:"Đề kiểm tra Toán lớp 6 tập 1", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:5, views:5200, editions:44, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:120, coverColor:"#F0D5A0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/8/22/image-book-20250822103655323.jpg", description:"Tuyển tập đề kiểm tra Toán lớp 6.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:57, title:"Để học tốt Tiếng Việt 3 tập 2", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:5, views:6100, editions:58, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:140, coverColor:"#F5C0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/8/26/image-book-20250826111445887.png", description:"Tài liệu hỗ trợ học tốt Tiếng Việt lớp 3.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:58, title:"Bộ câu hỏi trắc nghiệm đúng sai Toán 12", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"25.000 đ", rating:5, views:8900, editions:76, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:200, coverColor:"#FFE0B0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/9/3/image-book-20250903104126205.jpg", description:"Bộ câu hỏi trắc nghiệm Toán 12 theo chương trình mới.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:59, title:"Chinh phục các bài Toán khó lớp 8", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"25.000 đ", rating:5, views:7300, editions:62, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:180, coverColor:"#D8F0D0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/8/26/image-book-2025082611374253.jpg", description:"Chinh phục các bài toán khó lớp 8.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:60, title:"Để học tốt Ngữ văn 12 tập 2", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"25.000 đ", rating:5, views:9500, editions:88, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:250, coverColor:"#E0D0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/9/4/image-book-20250904144722442.jpg", description:"Hướng dẫn học tốt Ngữ văn 12 tập 2.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:61, title:"Văn tự sự, miêu tả", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"6.400 đ", rating:5, views:3600, editions:31, categories:["Sách tham khảo","Giáo dục"], genre:"Sách tham khảo", pages:110, coverColor:"#F0E0C0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/8/26/image-book-2025082611242307.jpg", description:"Hướng dẫn viết văn tự sự và miêu tả.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" },
  { id:62, title:"Thế giới quanh em", author:"Nhiều Tác Giả", publisher:"Benito", type:"Ebook", isVip:false, price:"5.000 đ", rating:5, views:5400, editions:46, categories:["Sách Thiếu nhi","Khoa học"], genre:"Sách Thiếu nhi", pages:60, coverColor:"#C0E0F0", coverImage:"https://images.sachbanquyen.com.vn/Thumbs/2025/8/18/image-book-20250818101232634.jpg", description:"Khám phá thế giới xung quanh em qua góc nhìn khoa học thú vị.", readTrialUrl:"https://sachbanquyen.com.vn/doc-thu/23314" }
];

// Sidebar data
const CATEGORIES = [
  {
    title: "DANH MỤC SÁCH CỦA BẠN",
    items: [
      { name: "Sách tham khảo và bồi dưỡng nâng cao", children: ["Sách tham khảo theo môn học", "Sách luyện thi và ôn tập", "Sách bồi dưỡng học sinh giỏi"] },
      { name: "Sách khoa học và kỹ năng sống", children: ["Sách khoa học phổ thông", "Sách kỹ năng sống và giáo dục đạo đức"] },
      { name: "Sách văn học và nghệ thuật", children: ["Văn học Việt Nam", "Văn học nước ngoài", "Nghệ thuật"] },
      { name: "Sách lịch sử, địa lý và văn hóa", children: ["Lịch sử", "Địa lý", "Văn hóa và xã hội"] },
      { name: "Sách ngoại ngữ", children: ["Tiếng Anh", "Các ngoại ngữ khác"] }
    ]
  },
  {
    title: "PHÂN LOẠI THEO BỘ SÁCH",
    items: [
      { name: "Danh mục Cấp I", children: ["Danh mục Cấp I - 1", "Danh mục Cấp I - 2", "Danh mục Cấp I - 3"] },
      { name: "Danh mục Cấp I - 2", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] },
      { name: "Danh mục Cấp I - 3", children: ["Danh mục Cấp II - 1", "Danh mục Cấp II - 2", "Danh mục Cấp II - 3"] }
    ]
  }
];

const TOPICS = [
  "Truyện cổ tích",
  "Tác phẩm kinh điển",
  "Văn học thiếu nhi",
  "Truyện tranh Nhật Bản",
  "Chăm sóc sức khoẻ trẻ em",
  "Kinh tế - Chính trị - Xã hội",
  "Tâm lý học"
];

const AUTHORS_LIST = [
  "Nguyễn Nhật Ánh",
  "Phan Thị Vàng Anh",
  "Trần Tùng Chinh",
  "Nguyễn Văn Anh",
  "Hoàng Liên",
  "Xuân Quỳnh",
  "Nguyễn Mỹ Nữ"
];

const LANGUAGES = ["Tiếng Việt", "Tiếng Anh", "Tiếng Trung"];

const AGE_GROUPS = ["Dưới 5 tuổi", "6-11 tuổi", "12 -15 tuổi", "15 - 18 tuổi", "Trên 18 tuổi"];

// Simulated book content for Reader Mode
const SAMPLE_BOOK_CONTENT = `
<h2>Chương 1: Khởi Đầu</h2>
<p>Trong một buổi sáng đẹp trời, khi ánh nắng vàng óng chiếu xuyên qua tán lá, câu chuyện của chúng ta bắt đầu. Đó là một ngày bình thường như bao ngày khác, nhưng lại mang đến những thay đổi phi thường cho nhân vật chính của câu chuyện.</p>
<p>Người ta thường nói rằng cuộc đời là một cuốn sách, và mỗi người trong chúng ta đều là tác giả của cuốn sách ấy. Có những trang lật qua nhanh chóng, có những trang khiến ta muốn dừng lại, đọc đi đọc lại nhiều lần. Nhưng điều quan trọng nhất là mỗi trang đều có ý nghĩa riêng của nó.</p>
<p>Năm ấy, tôi mới hai mươi tuổi, cái tuổi đầy hoài bão và ước mơ. Thế giới trong mắt tôi lúc đó rộng lớn và đầy màu sắc, như một bức tranh khổng lồ đang chờ tôi tô vẽ.</p>

<h2>Chương 2: Hành Trình</h2>
<p>Mỗi hành trình đều bắt đầu bằng một bước chân đầu tiên. Đôi khi bước chân ấy vững vàng và tự tin, nhưng đôi khi nó run rẩy và do dự. Không sao cả, vì điều quan trọng không phải là bước chân ấy mạnh mẽ đến đâu, mà là bạn có dám bước hay không.</p>
<p>Tôi lên đường vào một buổi chiều tháng Tám, khi cơn mưa vừa tạnh và trời bắt đầu hửng nắng. Hành lý của tôi chỉ có một chiếc ba lô nhỏ, vài bộ quần áo, và một cuốn sổ tay cũ kỹ.</p>
<p>Con đường phía trước dài và quanh co, nhưng tôi biết rằng mỗi khúc quanh đều ẩn chứa một bài học. Những người tôi gặp trên đường, những câu chuyện tôi được nghe, tất cả đều ghép lại thành một bức tranh lớn hơn về cuộc sống.</p>
<p>Có lúc tôi cảm thấy cô đơn, nhưng chính trong sự cô đơn ấy, tôi tìm thấy sức mạnh. Sức mạnh để tiếp tục bước đi, để không bỏ cuộc khi mọi thứ trở nên khó khăn.</p>

<h2>Chương 3: Bài Học</h2>
<p>Những bài học quý giá nhất trong cuộc sống thường đến từ những nơi ta ít ngờ nhất. Đôi khi chúng đến từ một người lạ mặt trên chuyến xe buýt, đôi khi từ tiếng cười của một đứa trẻ, và đôi khi từ chính những thất bại đau đớn nhất.</p>
<p>Tôi đã học được rằng thành công không phải là đích đến, mà là một hành trình. Và trên hành trình ấy, điều quan trọng nhất không phải là ta đi nhanh đến đâu, mà là ta có đang đi đúng hướng hay không.</p>
<p>Cuộc sống không phải lúc nào cũng công bằng, nhưng nó luôn công bằng theo cách riêng của mình. Mỗi khó khăn đều mang đến một cơ hội, mỗi thất bại đều chứa đựng một bài học.</p>
<p>Khi tôi nhìn lại hành trình của mình, tôi nhận ra rằng mọi thứ đều có lý do. Những người tôi đã gặp, những nơi tôi đã đến, tất cả đều góp phần tạo nên con người tôi hôm nay.</p>

<h2>Chương 4: Trở Về</h2>
<p>Sau tất cả những ngày tháng lang thang, tôi trở về nhà. Nhưng tôi không còn là người đã ra đi năm ấy nữa. Tôi đã thay đổi, đã trưởng thành, đã hiểu thêm nhiều điều về cuộc sống và về chính bản thân mình.</p>
<p>Nhà vẫn vậy, với mái ngói đỏ và hàng rào hoa giấy. Mẹ vẫn ngồi đó, ở chiếc ghế mây quen thuộc, đợi tôi với nụ cười hiền hậu. Và trong khoảnh khắc ấy, tôi hiểu rằng đôi khi, hành trình xa xôi nhất lại dẫn ta trở về nơi bắt đầu.</p>
<p>Tôi viết cuốn sách này không phải để kể về mình, mà để chia sẻ những bài học tôi đã nhận được. Bởi vì tôi tin rằng mỗi người đều có một câu chuyện đáng để kể, và mỗi câu chuyện đều có thể thay đổi cuộc đời ai đó.</p>
`;
